In [1]:
import os
import pandas as pd

In [ ]:
df = pd.read_csv('/home/vault/empkins/tpD/D02/RCT/raw_data/516/516_t2_20240213.txt' , skiprows=21, sep="\t", header=None)
#df = pd.read_csv('/home/hpc/iwso/iwso108h/raw_data/038/038_t2_20230303.txt' , skiprows=25, sep="\t", header=None)

In [38]:
df.head(5)

,0,1,2,3,4,5,6,7,8
0,0.0,-0.000488,6.75018,0.015259,-0.037994,2.478030,0.173187,-0.321045,NaN
1,0.5,-0.002197,6.75110,0.013123,-0.021515,0.885925,-0.299530,-0.316925,NaN
2,1.0,-0.003479,6.75018,0.014191,0.010986,-0.673523,-0.543213,-0.313568,NaN
3,1.5,0.000732,6.75140,0.016480,0.028534,-0.719299,-0.438995,-0.312347,NaN
4,2.0,-0.000305,6.75110,0.016632,0.014954,0.207825,-0.042267,-0.313568,NaN

In [39]:
#df.drop(columns=[0, 1, 7, 8, 10], inplace=True, axis=1)
df.drop(columns=[0, 1, 8], inplace=True, axis=1)

In [40]:
df.columns = ['RSP','Corrugator','Oculi','Zygomaticus','Masseter','ECG']

In [41]:
df.head()

       RSP  Corrugator     Oculi  Zygomaticus  Masseter       ECG
0  6.75018    0.015259 -0.037994     2.478030  0.173187 -0.321045
1  6.75110    0.013123 -0.021515     0.885925 -0.299530 -0.316925
2  6.75018    0.014191  0.010986    -0.673523 -0.543213 -0.313568
3  6.75140    0.016480  0.028534    -0.719299 -0.438995 -0.312347
4  6.75110    0.016632  0.014954     0.207825 -0.042267 -0.313568

In [42]:
df.shape

(9541507, 6)

In [43]:
df.to_csv("/home/woody/iwso/iwso108h/Processed_Data/Depressed/471/PreProcessed.csv", index=False)